language: python
python:
      - '3.8'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pur_beurre_V2_app.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
