language: python
python:
      - '3.8'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  #- pip install pipenv
  #- pipenv install

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
